config/routes.rb
require Rails.root.join('lib', 'superadmin', 'mailer_preview_constraint')

Rails.application.routes.draw do
  root to: 'root#new'

  scope :superadmin do
    mount Sidekiq::Web => '/sidekiq'

    # unless Rails.env.production?
    #   get(
    #     '/rails/mailers' => 'rails/mailers#index',
    #     constraints: Superadmin::MailerPreviewConstraint.new,
    #     as: 'superadmin_rails_mailers'
    #   )

    #   get(
    #     '/rails/mailers/*path' => 'rails/mailers#preview',
    #     constraints: Superadmin::MailerPreviewConstraint.new
    #   )
    # end
  end

  # === SUMMARY OF DEVISE ROUTES
  #
  # Items labeled `[UI]` have a corresponding view under `app/view/users/*`
  #
  # +-------------------------------+--------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
  # | `devise/confirmations#new`    | `GET    /users/confirmation/new`     | [UI] to send (or re-send) confirmation email                                                                                   |
  # | `devise/confirmations#create` | `POST   /users/confirmation`         | Generate confirmation email. Called by `#new`                                                                                  |
  # | `devise/confirmations#show`   | `GET    /users/confirmation`         | Validate confirmation. Linked from email. If valid, redirect to `root_path`. If invalid, render `:new` to re-send confirmation.|
  # +-------------------------------+--------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
  # | `devise/passwords#new`        | `GET    /users/password/new `        | [UI] to reset password                                                                                                         |
  # | `devise/passwords#create`     | `POST   /users/password`             | Generate "reset password" email. Called by `#new`. If errors, renders the `#new` template                                      |
  # | `devise/passwords#edit`       | `GET    /users/password/edit`        | [UI] to update the password. Linked from email.                                                                                |
  # | `devise/passwords#update`     | `PUT    /users/password`             | Update the password. Called from `:edit`. If errors, renders the `#new` template                                               |
  # +-------------------------------+--------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
  # | `devise/registrations#new`    | `GET    /users/registrations/new`    | [UI] to sign up (create a new User)                                                                                            |
  # | `devise/registrations#create` | `POST   /users/registrations`        | Create new user. Called by `#new`. If errors, renders the `#new` template                                                      |
  # | `devise/registrations#edit`   | `GET    /users/registrations/edit`   | [UI] to edit a User (UNUSED) - overridden to redirect to `/account`                                                            |
  # | `devise/registrations#update` | `PUT    /users/registrations`        | Updates a user's password only. Called from `/account`                                                                         |
  # | `devise/registrations#cancel` | `GET    /users/registrations/cancel` | Unused. See Devise's `RegistrationController` for description                                                                  |
  # | `devise/registrations#destroy`| `DELETE /users/registrations`        | Delete a User                                                                                                                  |
  # +-------------------------------+--------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
  # | `devise/sessions#new`         | `GET    /users/log-in`               | [UI] to log in                                                                                                                 |
  # | `devise/sessions#create`      | `POST   /users/log-in`               | Create a new session. Called from `#new`                                                                                       |
  # | `devise/sessions#destroy`     | `GET    /users/log-out`              | Log out                                                                                                                        |
  # +-------------------------------+--------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+

  devise_for(
    :users,
    controllers: {
      confirmations: 'devise/custom/confirmations',
      omniauth_callbacks: 'devise/custom/omniauth_callbacks',
      passwords: 'devise/custom/passwords',
      registrations: 'devise/custom/registrations',
      sessions: 'devise/custom/sessions'
    },
    path_names: {
      sign_in: 'log-in',
      sign_out: 'log-out',
      sign_up: 'new',
      registration: 'registrations'
    },
    sign_out_via: :get
  )

  resources :account, only: %i[index]

  namespace :api, defaults: { format: 'json' } do
    scope path: 'v1', module: :v1, as: :v1 do
      resources :users, only: %i[index show update destroy] do
        post :add_role
        post :remove_role
      end
      resources :user_invitations, only: %i[index create destroy] do
        post :resend
      end
    end
  end

  resources :deactivated_users, only: %i[index destroy]

  resources :photos, only: :index

  resources :product_feedbacks, only: :create

  resources :settings, only: %i[index]
  namespace :settings do
    resources :users, only: %i[index]
    resources :user_roles, only: %i[update]
  end

  resources :users, only: %i[index destroy]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  include SerializationHelper
  include WebpackHelper

  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :check_if_deactivated
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :append_view_paths
  before_action :initialize_packs_list
  before_action :set_default_pack

  helper_method :view_context

  unless Rails.env.development?
    rescue_from Exception do |exception|
      respond_to do |format|
        format.html { render plain: '500 Internal Server Error', status: 500 }

        format.json do
          error = { title: 'An unknown error occurred', status: '500' }
          render json: { errors: [error] }, status: 500
        end
      end
    end

    rescue_from ActiveRecord::RecordNotFound do |exception|
      respond_to do |format|
        format.html { render plain: '404 Not Found', status: 404 }

        format.json do
          error = {
            title: 'Not Found',
            description: exception.message,
            status: '404'
          }
          render json: { errors: [error] }, status: 404
        end
      end
    end

    rescue_from CanCan::AccessDenied do |exception|
      respond_to do |format|
        format.html { render plain: '403 Forbidden', status: 403 }

        format.json do
          error = { title: 'Forbidden', status: '403' }
          render json: { errors: [error] }, status: 403
        end
      end
    end
  end

  private

  def user
    @user ||=
      User.find_by_synthetic_id!(params[:user_invitation_id] || params[:id])
  end

  def user_invitation
    @user_invitation ||=
      UserInvitation.find(params[:user_invitation_id] || params[:id])
  end

  def ensure_json_request
    return if defined?(request) && request.format.to_sym == :json
    redirect_to(root_path)
  end

  def append_view_paths
    append_view_path 'app/views/application'
  end

  def initialize_packs_list
    @use_packs = []
  end

  def set_default_pack
    @use_packs << 'common'

    # This pack should only be included in the test environment. It includes
    # JQuery so the Capybara tests can use it
    @use_packs << 'jquery-for-test' if Rails.env.test?
  end

  def verifier
    @verifier ||=
      ActiveSupport::MessageVerifier.new(
        Rails.application.secrets[:secret_key_base]
      )
  end

  # Devise calls `authenticate_user!` but skips actually authenticating users
  # in some instances where we might want to enforce authentication.
  # Use this `before_action` to foce authentication.
  def force_authenticate_user!
    authenticate_user!(force: true)
  end

  protected

  def check_if_deactivated
    return unless user_signed_in? && current_user.deactivated?

    respond_to do |format|
      format.json { render json: { error: 'User is deactivated' }, status: 403 }
      format.html { redirect_to(deactivated_users_path) }
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_presenter
    @current_user_presenter ||=
      (UserPresenter.new(current_user, view: view_context) if current_user)
  end

  # Devise
  def devise_mapping
    Devise.mappings[:user]
  end

  # Devise automatically sets a flash `notice` on succesful sign in.
  # This hacky workaround removes the flash if it is set.
  def after_sign_in_path_for(resource)
    flash.delete(:notice) if flash[:notice] == t('devise.sessions.signed_in')
    super
  end

  # Devise automatically sets a flash `notice` on succesful sign out.
  # This hacky workaround removes the flash if it is set.
  def after_sign_out_path_for(resource)
    flash.delete(:notice) if flash[:notice] == t('devise.sessions.signed_out')
    super
  end

  def page_specific_css_id
    @page_specific_css_id ||=
      "#{params[:controller]}-#{params[:action]}".tr('_', '-').tr('/', '-')
  end

  def render_inside(opts = {}, &block)
    layout = opts.fetch(:parent_layout)

    layout = "layouts/#{layout}" unless layout.start_with?('layout')
    content_for(:nested_layout_content, capture(&block))
    render template: layout
  end

  # Creates a DOM node on which a React component can be mounted. Encodes
  # props into the `data-react-props` attribute so they can be parsed and
  # passed into the component by client-side JS
  def react_component(mount_id, props)
    id = "react-mount-#{mount_id}"

    content_tag(:div, id: id, data: { react_props: props }) {}
  end

  def to_bool(value)
    ActiveRecord::Type::Boolean.new.deserialize(value)
  end

  # Serialize a collection of objects using an existing serializer
  #
  # e.g.
  #   -> serialize(Foo)
  #   -> serialize(Foo, collection: Foo.where("id < ?", 10))
  def serialize(klass, opts = {})
    collection = opts[:collection] || klass.order(:id)
    serializer = "#{klass}Serializer".constantize

    options = { params: {} }.deep_merge(opts)

    serializer.new(collection, options).serializable_hash
  end

  # Useful for translating param `:id` values from :synthetic_id to :id.
  # Raises `ActiveRecord::RecordNotFound` if not found
  def translate_synthetic_id!(id, klass = User)
    return if id.blank?

    klass
      .find_by_synthetic_id(id)
      .tap do |record|
        if record.nil?
          raise(
            ActiveRecord::RecordNotFound,
            "Couldn't find #{klass} with 'synthetic_id'=#{id}"
          )
        end
      end
      .id
  end
end

app/views/application/_desktop_header.html.erb
<div class="desktop-header">
  <div class="desktop-header__profile-pic">
    <%= link_to(root_path) do %>
      <img src="<%= current_user_presenter.avatar.dig(:url, :thumb) %>" />
    <% end %>
  </div>

  <!--
    Mobile menu is just a single consolidated menu, but a desktop menu can have
    multiple dropdowns. So we have to distinguish dropdowns by name
    e.g. "Account Dropdown"
  -->

  <!-- Account Dropdown -->
  <nav class="desktop-header-account-dropdown soft-shadow inactive">
    <ul class="desktop-header-account-dropdown__links">
      <li class="desktop-header-account-dropdown__link-element">
        <%= link_to(t(".links.my_photos"), photos_path) %>
      </li>

      <li class="desktop-header-account-dropdown__link-element">
        <%= link_to(t(".links.account"), account_index_path) %>
      </li>

      <li class="desktop-header-account-dropdown__link-element desktop-header-account-dropdown__link-element--settings">
        <%= link_to(settings_path) do %>
          <%=t(".links.settings") %>
        <% end %>
      </li>

      <li class="desktop-header-account-dropdown__link-element desktop-header-account-dropdown__link-element--product-feedback">
        <%= link_to("#") do %>
          <%= t(".links.product_feedback") %>
          <%= inline_svg_tag("icons/speaker.svg", width: "22px", height: "22px") %>
        <% end %>
      </li>

      <li class="desktop-header-account-dropdown__link-element">
        <%= link_to(t(".links.log_out"), destroy_user_session_path) %>
      </li>
    </ul>
  </nav>
</div>

app/views/application/_mobile_header.html.erb
<div class="mobile-header">
  <div class="mobile-header__menu-icon">
    <%= inline_svg_tag("icons/menu.svg", height: "28px", width: "28px" ) %>
  </div>

  <div class="mobile-header__logo">
    <%= link_to(root_path) do %>
      <%= inline_svg_tag("logo.svg", height: "36px", width: "36px" ) %>
    <% end %>
  </div>
</div>

<nav class="mobile-header-dropdown inactive">
  <div class="mobile-header-dropdown__close">
    <%= inline_svg_tag("icons/x.svg", height: "24px", width: "24px" ) %>
  </div>

  <div class="mobile-header-dropdown__profile">
    <%= link_to(root_path) do %>
      <img src="<%= current_user_presenter.avatar.dig(:url, :thumb) %>" />
    <% end %>
    <span><%= current_user.first_name.downcase %></span>
  </div>

  <ul class="mobile-header-dropdown__links">
    <li class="mobile-header-dropdown__link-element">
      <%= link_to(t(".links.my_photos"), photos_path) %>
    </li>

    <li class="mobile-header-dropdown__link-element">
      <%= link_to(t(".links.account"), account_index_path) %>
    </li>

    <li class="mobile-header-dropdown__link-element mobile-header-dropdown__link-element--settings">
      <%= link_to(settings_path) do %>
        <%=t(".links.settings") %>
      <% end %>
    </li>

    <li class="mobile-header-dropdown__link-element mobile-header-dropdown__link-element--product-feedback">
      <%= link_to("#") do %>
        <%= t(".links.product_feedback") %>
        <%= inline_svg_tag("icons/speaker.svg", width: "22px", height: "22px") %>
      <% end %>
    </li>

    <li class="mobile-header-dropdown__link-element">
      <%= link_to(t(".links.log_out"), destroy_user_session_path) %>
    </li>
  </ul>
</nav>

<div class="mobile-header-dropdown__overlay inactive"></div>

app/views/application/_modal.html.erb
<!-- Mount point for react modals -->
<div id="modal"></div>

app/views/application/_settings_template.html.erb
<div class='settings-template'>
  <ul class='settings-template__menu'>
    <% nav_links.each do |nl| %>
    <li class='<%= 'selected' if nl[:selected] %>'>
      <a href=<%= nl[:path] %>>
        <%= nl[:label] %>
      </a>
    </li>
    <% end %>
  </ul>

  <div class='settings-template__content'>
    <%= render 'layouts/flash', flash: flash %>
    <% if heading.present? %>
    <p class='settings-template__heading'><%= heading %></p>
    <% end %>

    <%= yield %>
  </div>
</div>